import type { ComplianceRule } from "../../../types";

export const AI_ACT_001: ComplianceRule = {
  id: "AI-ACT-001",
  framework: "eu-ai-act",
  version: "1.0.0",
  article: "Article 50",
  legalText:
    "Providers shall ensure that AI systems intended to interact directly with natural persons are designed and developed in such a way that the natural persons concerned are informed that they are interacting with an AI system.",
  legalSource: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
  legalRisk: "Up to €15,000,000 or 3% of total worldwide annual turnover",
  severity: "HIGH",
  title: "AI-generated output not labelled as such",
  description:
    "Detects chat / completion endpoints that return AI-generated text directly to end users without an accompanying disclosure that the response is AI-generated.",
  codePatterns: [
    "anthropic\\.messages\\.create",
    "openai\\.chat\\.completions\\.create",
    "createChatCompletion\\(",
  ],
  keywords: ["chat", "completion", "assistant", "chatbot", "AI", "model", "respond"],
  fileTypes: [".ts", ".tsx", ".js", ".jsx", ".py", ".rb"],
  violationExamples: [
    "const reply = await openai.chat.completions.create({...}); res.json({ message: reply });",
    "return new Response(text); // text comes from a Claude call",
  ],
  complianceExamples: [
    "res.json({ message: reply, source: 'ai', disclosure: 'This response was generated by an AI assistant.' });",
  ],
  findingTemplate: {
    explanation:
      "{{SPECIFIC_CODE}} returns AI-generated content to a natural person without disclosure. Article 50(1) of the EU AI Act requires that natural persons be informed they are interacting with an AI system, unless this is obvious from context to a reasonably well-informed user.",
    fixDescription:
      "Surface a clear, machine-readable disclosure (banner, message prefix, structured field) that identifies the response as AI-generated. Persist the disclosure in the response payload so client code cannot accidentally strip it.",
    fixCodeTemplate:
      "return Response.json({\n  message: reply,\n  source: 'ai',\n  disclosure: 'This response was generated by an AI assistant. Please verify before relying on it.',\n});",
    estimatedFixTime: "~30 minutes",
    references: [
      "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
      "https://artificialintelligenceact.eu/article/50/",
    ],
  },
};
