import type { ComplianceRule } from "./types";

export const AI_ACT_001: ComplianceRule = {
  id: "AI-ACT-001",
  framework: "eu-ai-act",
  version: "1.0.0",
  article: "Article 50",
  legalText:
    "Providers shall ensure that AI systems intended to interact directly with natural persons are designed and developed in such a way that the natural persons concerned are informed that they are interacting with an AI system.",
  legalSource: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
  legalRisk: "Up to €15,000,000 or 3% of total worldwide annual turnover",
  severity: "HIGH",
  title: "AI-generated output not labelled as such",
  description:
    "Detects chat / completion endpoints that return AI-generated text directly to end users without an accompanying disclosure that the response is AI-generated.",
  codePatterns: [
    "anthropic\\.messages\\.create",
    "openai\\.chat\\.completions\\.create",
    "createChatCompletion\\(",
  ],
  keywords: ["chat", "completion", "assistant", "chatbot", "AI", "model", "respond"],
  fileTypes: [".ts", ".tsx", ".js", ".jsx", ".py", ".rb"],
  violationExamples: [
    "const reply = await openai.chat.completions.create({...}); res.json({ message: reply });",
    "return new Response(text); // text comes from a Claude call",
  ],
  complianceExamples: [
    "res.json({ message: reply, source: 'ai', disclosure: 'This response was generated by an AI assistant.' });",
  ],
  findingTemplate: {
    explanation:
      "{{SPECIFIC_CODE}} returns AI-generated content to a natural person without disclosure. Article 50(1) of the EU AI Act requires that natural persons be informed they are interacting with an AI system, unless this is obvious from context to a reasonably well-informed user.",
    fixDescription:
      "Surface a clear, machine-readable disclosure (banner, message prefix, structured field) that identifies the response as AI-generated. Persist the disclosure in the response payload so client code cannot accidentally strip it.",
    fixCodeTemplate:
      "return Response.json({\n  message: reply,\n  source: 'ai',\n  disclosure: 'This response was generated by an AI assistant. Please verify before relying on it.',\n});",
    estimatedFixTime: "~30 minutes",
    references: [
      "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
      "https://artificialintelligenceact.eu/article/50/",
    ],
  },
};

export const AI_ACT_002: ComplianceRule = {
  id: "AI-ACT-002",
  framework: "eu-ai-act",
  version: "1.0.0",
  article: "Article 14",
  legalText:
    "High-risk AI systems shall be designed and developed in such a way, including with appropriate human-machine interface tools, that they can be effectively overseen by natural persons during the period in which they are in use.",
  legalSource: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
  legalRisk: "Up to €15,000,000 or 3% of total worldwide annual turnover",
  severity: "CRITICAL",
  title: "Automated decision affecting individuals without human-review path",
  description:
    "Detects AI-driven approval/rejection decisions over individuals (loans, hires, admissions, benefits) where the resulting status is set without a documented human-in-the-loop review step.",
  codePatterns: [
    "(approval|approved|reject|rejected|hired|fired|grant|denied)\\s*=\\s*ai",
    "(decision|verdict|outcome)\\s*=\\s*await\\s+(claude|openai|anthropic)",
    "user\\.(approved|status)\\s*=\\s*await\\s+(claude|openai|anthropic|model)",
  ],
  keywords: [
    "approval",
    "decision",
    "applicant",
    "candidate",
    "hire",
    "loan",
    "credit",
    "benefit",
    "eligibility",
  ],
  fileTypes: [".ts", ".tsx", ".js", ".jsx", ".py", ".rb"],
  violationExamples: [
    "applicant.status = decision === 'approve' ? 'hired' : 'rejected'; // decision comes from Claude",
    "const verdict = await openai.chat.completions.create(...); await updateLoanStatus(verdict);",
  ],
  complianceExamples: [
    "await queueForHumanReview(applicantId, aiSuggestion);",
    "if (aiSuggestion.confidence < 0.95 || HUMAN_REVIEW_REQUIRED) await queueForHumanReview(...);",
  ],
  findingTemplate: {
    explanation:
      "{{SPECIFIC_CODE}} commits an AI-suggested decision to the user record without a human-review gate. Article 14 of the EU AI Act requires high-risk AI systems to be effectively overseen by natural persons; decisions affecting an individual's rights or status must remain human-controllable.",
    fixDescription:
      'Persist the AI output as a recommendation, not a final state. Route the decision through a queue or status "pending_review" until a human reviewer confirms.',
    fixCodeTemplate:
      "await db.applicants.update({\n  id: applicantId,\n  data: { ai_suggestion: decision, status: 'pending_review' },\n});\nawait notifyReviewer(applicantId);",
    estimatedFixTime: "Half day",
    references: [
      "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
      "https://artificialintelligenceact.eu/article/14/",
    ],
  },
};

export const AI_ACT_003: ComplianceRule = {
  id: "AI-ACT-003",
  framework: "eu-ai-act",
  version: "1.0.0",
  article: "Article 53",
  legalText:
    "Providers of general-purpose AI models shall draw up and keep up-to-date the technical documentation of the model, including its training and testing process and the results of its evaluation.",
  legalSource: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
  legalRisk: "Up to €15,000,000 or 3% of total worldwide annual turnover",
  severity: "MEDIUM",
  title: "GPAI model used without documented capabilities and limitations",
  description:
    "Flags codebases that integrate a general-purpose AI model (Claude, GPT, Gemini, Mistral, Llama) without an accompanying model-card, README section, or `MODEL_CARD.md` describing intended use, evaluation results and known limitations.",
  codePatterns: [
    "anthropic\\.messages\\.create",
    "openai\\.chat\\.completions",
    "google\\.generativelanguage",
    "mistralai\\.client",
    "Llama|llama-2|llama-3|llama2",
  ],
  keywords: ["MODEL_CARD", "model card", "intended use", "limitations", "evaluation"],
  fileTypes: [".md", ".ts", ".js", ".py"],
  violationExamples: ["// project uses claude-sonnet-4-6 — no MODEL_CARD.md anywhere in the repo"],
  complianceExamples: [
    "// docs/MODEL_CARD.md describes intended use, training data, eval results, limitations",
  ],
  findingTemplate: {
    explanation:
      "{{SPECIFIC_CODE}} consumes a general-purpose AI model without supplementary documentation. Article 53 of the EU AI Act requires GPAI providers and downstream deployers to maintain technical documentation describing the model's training, evaluation and intended use.",
    fixDescription:
      "Add a `docs/MODEL_CARD.md` (or README section) covering: (1) intended use, (2) out-of-scope use, (3) the upstream model + version, (4) evaluation results you rely on, (5) known limitations and bias considerations.",
    fixCodeTemplate:
      "# Model Card — Themida Compliance Scanner\n\n## Upstream model\nclaude-sonnet-4-6 + claude-haiku-4-5 (Anthropic).\n\n## Intended use\n... \n\n## Out-of-scope use\n...\n\n## Evaluation\n...\n\n## Limitations\n...\n",
    estimatedFixTime: "Half day",
    references: [
      "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
      "https://artificialintelligenceact.eu/article/53/",
    ],
  },
};

export const AI_ACT_004: ComplianceRule = {
  id: "AI-ACT-004",
  framework: "eu-ai-act",
  version: "1.0.0",
  article: "Article 5(1)(h)",
  legalText:
    "The use of real-time remote biometric identification systems in publicly accessible spaces for the purposes of law enforcement shall be prohibited, save for limited and strictly defined exceptions.",
  legalSource: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
  legalRisk: "Up to €35,000,000 or 7% of total worldwide annual turnover",
  severity: "CRITICAL",
  title: "Biometric identification without an explicit lawful basis",
  description:
    "Detects use of facial recognition, fingerprint matching, voice-print or other biometric identification APIs without surrounding code that gates access by an explicit lawful basis or `consent`/`law_enforcement_warrant` flag.",
  codePatterns: [
    "rekognition\\.(searchFaces|compareFaces)",
    "face[-_]?api\\.detect",
    "azure-cognitiveservices-vision-face",
    "biometric|fingerprint|face_match|voice_print",
  ],
  keywords: ["rekognition", "face", "fingerprint", "biometric", "voiceprint", "iris"],
  fileTypes: [".ts", ".tsx", ".js", ".jsx", ".py"],
  violationExamples: [
    "const match = await rekognition.searchFacesByImage({ CollectionId: 'visitors', ... });",
  ],
  complianceExamples: [
    "if (!warrant && !explicitConsent) throw new Error('biometric identification not permitted'); ",
  ],
  findingTemplate: {
    explanation:
      "{{SPECIFIC_CODE}} performs biometric identification without a visible lawful-basis gate. Article 5 of the EU AI Act prohibits real-time remote biometric identification in publicly accessible spaces except under narrowly defined exceptions, and Article 6 requires high-risk AI systems to document a lawful basis.",
    fixDescription:
      "Wrap the call in a lawful-basis check (explicit consent, contractual necessity, or — for law enforcement — a documented warrant). Log the basis with each invocation.",
    fixCodeTemplate:
      "if (!hasExplicitBiometricConsent(user) && !lawfulBasis.warrant) {\n  throw new ForbiddenError('biometric identification requires a lawful basis');\n}\nconst match = await rekognition.searchFacesByImage(...);",
    estimatedFixTime: "1-2 hours",
    references: [
      "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
      "https://artificialintelligenceact.eu/article/5/",
    ],
  },
};

export const AI_ACT_005: ComplianceRule = {
  id: "AI-ACT-005",
  framework: "eu-ai-act",
  version: "1.0.0",
  article: "Article 5(1)(f)",
  legalText:
    "The placing on the market, the putting into service for this specific purpose, or the use of AI systems to infer emotions of a natural person in the areas of workplace and education institutions shall be prohibited.",
  legalSource: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
  legalRisk: "Up to €35,000,000 or 7% of total worldwide annual turnover",
  severity: "CRITICAL",
  title: "Emotion-recognition AI used in workplace or education context",
  description:
    "Flags imports of emotion-recognition libraries or API calls (`detect_emotion`, `face_emotion`, sentiment-from-camera) when the surrounding code references HR / employee / student / classroom contexts.",
  codePatterns: [
    "detect_?emotion",
    "face[-_]?emotion",
    "sentiment.*camera",
    "(employee|hr|student|classroom).*emotion",
  ],
  keywords: ["emotion", "sentiment", "employee", "student", "classroom", "hr", "workplace"],
  fileTypes: [".ts", ".tsx", ".js", ".jsx", ".py"],
  violationExamples: [
    "const mood = await detectEmotion(employeeWebcamFrame);",
    "if (student.classroomMood === 'distracted') alertTeacher();",
  ],
  complianceExamples: [
    "// emotion recognition disabled in workplace/education — see compliance/eu-ai-act.md",
  ],
  findingTemplate: {
    explanation:
      "{{SPECIFIC_CODE}} performs emotion recognition in a workplace or education context. Article 5(1)(f) of the EU AI Act prohibits the placing on the market and use of AI systems that infer emotions of natural persons in those settings, with very narrow exceptions for medical / safety reasons.",
    fixDescription:
      "Remove the emotion-recognition pipeline from the workplace/education flow, or document the safety/medical exception under Article 5(1)(f) with legal sign-off and surface that documentation in the code path.",
    fixCodeTemplate:
      "// Emotion recognition removed — Article 5(1)(f) of the EU AI Act prohibits this in workplace/education contexts.",
    estimatedFixTime: "Half day",
    references: [
      "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
      "https://artificialintelligenceact.eu/article/5/",
    ],
  },
};

export const EU_AI_ACT_RULES = [
  AI_ACT_001,
  AI_ACT_002,
  AI_ACT_003,
  AI_ACT_004,
  AI_ACT_005,
] as const;
