#!/usr/bin/env tsx
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as prettier from "prettier";

import { FRAMEWORK_REGISTRY } from "@/lib/rules/frameworks/registry";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const DOC_PATH = path.join(ROOT, "docs/reference/frameworks.md");

const BEGIN_MARKER =
  "<!-- BEGIN:frameworks-table (generated by scripts/generate-frameworks-doc.mts — do not edit by hand; run `pnpm docs:generate`) -->";
const END_MARKER = "<!-- END:frameworks-table -->";

/** Build the markdown table for every pack in the registry (the source of truth). */
function buildTable(): string {
  const header = ["| Framework | Status | Rules | Source |", "| --- | --- | --- | --- |"];
  const rows = Object.values(FRAMEWORK_REGISTRY).map((pack) => {
    const { id, displayName, regulationUrl, ruleIdPrefix } = pack.meta;
    const count = pack.rules.length;
    const first = `\`${ruleIdPrefix}-001\``;
    const last = `\`${ruleIdPrefix}-${String(count).padStart(3, "0")}\``;
    const rules = count === 1 ? `1 (${first})` : `${count} (${first}–${last})`;
    const source = `[\`src/lib/rules/frameworks/${id}/\`](../../src/lib/rules/frameworks/${id}/)`;
    return `| [${displayName}](${regulationUrl}) | Shipped | ${rules} | ${source} |`;
  });
  return [...header, ...rows].join("\n");
}

/** Splice the freshly built table between the marker comments in `source`. */
function render(source: string): string {
  const begin = source.indexOf(BEGIN_MARKER);
  const end = source.indexOf(END_MARKER);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error(
      `frameworks.md is missing the generator markers. Expected:\n${BEGIN_MARKER}\n…\n${END_MARKER}`,
    );
  }
  const before = source.slice(0, begin + BEGIN_MARKER.length);
  const after = source.slice(end);
  return `${before}\n\n${buildTable()}\n\n${after}`;
}

async function format(markdown: string): Promise<string> {
  const config = (await prettier.resolveConfig(DOC_PATH)) ?? {};
  return prettier.format(markdown, { ...config, parser: "markdown" });
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const current = readFileSync(DOC_PATH, "utf8");
  const expected = await format(render(current));

  if (check) {
    if (current !== expected) {
      console.error(
        "docs/reference/frameworks.md is out of date with the rule registry.\n" +
          "Run `pnpm docs:generate` and commit the result.",
      );
      process.exit(1);
    }
    console.log("docs/reference/frameworks.md is up to date.");
    return;
  }

  if (current === expected) {
    console.log("docs/reference/frameworks.md already up to date.");
    return;
  }
  writeFileSync(DOC_PATH, expected);
  console.log("Updated docs/reference/frameworks.md from the rule registry.");
}

main().catch((err: unknown) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
